In [2]:
import pandas as pd
import numpy as np
import import_ipynb
import pickle
from decouple import Config, RepositoryEnv
import pymongo

In [3]:
data = pd.read_csv("../recipe_data/RAW_recipes.csv")
data.head()

,name,id,minutes,contributor_id,submitted,tags,nutrition,n_steps,steps,description,ingredients,n_ingredients
0,arriba baked winter squash mexican style,137739,55,47892,2005-09-16,"['60-minutes-or-less', 'time-to-make', 'course...","[51.5, 0.0, 13.0, 0.0, 2.0, 0.0, 4.0]",11,"['make a choice and proceed with recipe', 'dep...",autumn is my favorite time of year to cook! th...,"['winter squash', 'mexican seasoning', 'mixed ...",7
1,a bit different breakfast pizza,31490,30,26278,2002-06-17,"['30-minutes-or-less', 'time-to-make', 'course...","[173.4, 18.0, 0.0, 17.0, 22.0, 35.0, 1.0]",9,"['preheat oven to 425 degrees f', 'press dough...",this recipe calls for the crust to be prebaked...,"['prepared pizza crust', 'sausage patty', 'egg...",6
2,all in the kitchen chili,112140,130,196586,2005-02-25,"['time-to-make', 'course', 'preparation', 'mai...","[269.8, 22.0, 32.0, 48.0, 39.0, 27.0, 5.0]",6,"['brown ground beef in large pot', 'add choppe...",this modified version of 'mom's' chili was a h...,"['ground beef', 'yellow onions', 'diced tomato...",13
3,alouette potatoes,59389,45,68585,2003-04-14,"['60-minutes-or-less', 'time-to-make', 'course...","[368.1, 17.0, 10.0, 2.0, 14.0, 8.0, 20.0]",11,['place potatoes in a large pot of lightly sal...,"this is a super easy, great tasting, make ahea...","['spreadable cheese with garlic and herbs', 'n...",11
4,amish tomato ketchup for canning,44061,190,41706,2002-10-25,"['weeknight', 'time-to-make', 'course', 'main-...","[352.9, 1.0, 337.0, 23.0, 3.0, 0.0, 28.0]",5,['mix all ingredients& boil for 2 1 / 2 hours ...,my dh's amish mother raised him on this recipe...,"['tomato juice', 'apple cider vinegar', 'sugar...",8

In [4]:
df2 = pd.read_pickle('/recipe_data/ingr_map.pkl')
df2.head()

,raw_ingr,raw_words,processed,len_proc,replaced,count,id
0,"medium heads bibb or red leaf lettuce, washed,...",13,"medium heads bibb or red leaf lettuce, washed,...",73,lettuce,4507,4308
1,mixed baby lettuces and spring greens,6,mixed baby lettuces and spring green,36,lettuce,4507,4308
2,romaine lettuce leaf,3,romaine lettuce leaf,20,lettuce,4507,4308
3,iceberg lettuce leaf,3,iceberg lettuce leaf,20,lettuce,4507,4308
4,red romaine lettuce,3,red romaine lettuce,19,lettuce,4507,4308

In [5]:
ingr = df2[["replaced", "id"]]
ingr = ingr.drop_duplicates()

In [51]:
config = Config(RepositoryEnv("../../.env"))
client = pymongo.MongoClient(config("MONGODB_URL"))
db = client["recipe_data"]

In [7]:
upload_recipes = data.drop(columns=["contributor_id","submitted"])
upload_recipes.head()

,name,id,minutes,tags,nutrition,n_steps,steps,description,ingredients,n_ingredients
0,arriba baked winter squash mexican style,137739,55,"['60-minutes-or-less', 'time-to-make', 'course...","[51.5, 0.0, 13.0, 0.0, 2.0, 0.0, 4.0]",11,"['make a choice and proceed with recipe', 'dep...",autumn is my favorite time of year to cook! th...,"['winter squash', 'mexican seasoning', 'mixed ...",7
1,a bit different breakfast pizza,31490,30,"['30-minutes-or-less', 'time-to-make', 'course...","[173.4, 18.0, 0.0, 17.0, 22.0, 35.0, 1.0]",9,"['preheat oven to 425 degrees f', 'press dough...",this recipe calls for the crust to be prebaked...,"['prepared pizza crust', 'sausage patty', 'egg...",6
2,all in the kitchen chili,112140,130,"['time-to-make', 'course', 'preparation', 'mai...","[269.8, 22.0, 32.0, 48.0, 39.0, 27.0, 5.0]",6,"['brown ground beef in large pot', 'add choppe...",this modified version of 'mom's' chili was a h...,"['ground beef', 'yellow onions', 'diced tomato...",13
3,alouette potatoes,59389,45,"['60-minutes-or-less', 'time-to-make', 'course...","[368.1, 17.0, 10.0, 2.0, 14.0, 8.0, 20.0]",11,['place potatoes in a large pot of lightly sal...,"this is a super easy, great tasting, make ahea...","['spreadable cheese with garlic and herbs', 'n...",11
4,amish tomato ketchup for canning,44061,190,"['weeknight', 'time-to-make', 'course', 'main-...","[352.9, 1.0, 337.0, 23.0, 3.0, 0.0, 28.0]",5,['mix all ingredients& boil for 2 1 / 2 hours ...,my dh's amish mother raised him on this recipe...,"['tomato juice', 'apple cider vinegar', 'sugar...",8

In [8]:
upload_recipes["name"] = upload_recipes['name'].str.replace(r'\s+', ' ', regex=True).str.strip()
upload_recipes.iloc[452]["name"]

'magic cookie bars'

In [9]:
# MIGRATE RECIPES TO MONGODB

#recipe_col = db["recipes"]

#for j, row in upload_recipes.iterrows():
#    recipe_col.insert_one({
#        "name": row['name'], 
#        "id": row.id, 
#        "minutes": row.minutes,
#        "tags": row.tags,
#        "nutrition": row.nutrition,
#        "n_steps": row.n_steps,
#        "steps": row.steps,
#        "description": row.description,
#        "ingredients": row.ingredients,
#        "n_ingredients": row.n_ingredients,
#        })

In [10]:
# EXTRACTING ITEM IDS & RATINGS PER USER

pp_user = pd.read_csv("PP_users.csv")
print(pp_user.head())
pp_user["items"] = pp_user["items"].apply(lambda x:x[1:-1]).str.split(", ").apply(lambda x: [int(y) for y in x])

itemList_byUsers_sum = pp_user["items"].apply(lambda x: len(x)).sum()
print(itemList_byUsers_sum )

pp_user["ratings"] = pp_user["ratings"].apply(lambda x:x[1:-1]).str.split(", ").apply(lambda x: [float(y) for y in x])
rateList_byUsers_sum = pp_user["ratings"].apply(lambda x: len(x)).sum()
print(rateList_byUsers_sum)

   u                                         techniques  \
0  0  [8, 0, 0, 5, 6, 0, 0, 1, 0, 9, 1, 0, 0, 0, 1, ...
1  1  [11, 0, 0, 2, 12, 0, 0, 0, 0, 14, 5, 0, 0, 0, ...
2  2  [13, 0, 0, 7, 5, 0, 1, 2, 1, 11, 0, 1, 0, 0, 1...
3  3  [498, 13, 4, 218, 376, 3, 2, 33, 16, 591, 10, ...
4  4  [161, 1, 1, 86, 93, 0, 0, 11, 2, 141, 0, 16, 0...

                                               items  n_items  \
0  [1118, 27680, 32541, 137353, 16428, 28815, 658...       31
1  [122140, 77036, 156817, 76957, 68818, 155600, ...       39
2  [168054, 87218, 35731, 1, 20475, 9039, 124834,...       27
3  [163193, 156352, 102888, 19914, 169438, 55772,...     1513
4  [72857, 38652, 160427, 55772, 119999, 141777, ...      376

                                             ratings  n_ratings
0  [5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 4.0, 4.0, ...         31
1  [5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, ...         39
2  [3.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 5.0, ...         27
3  [5.0, 5.0, 5.0, 5.0, 4.0, 4.0, 5.0, 5.0, 5.0, ...       1513
4  [5.0, 5.0, 5.0, 5.0, 4.0, 4.0, 5.0, 4.0, 5.0, ...        376
698901
698901

In [58]:
# EXTRACTING INGREDIENT IDS

pp_rec = pd.read_csv("PP_recipes.csv")


pp_rec_fields = pp_rec[["id", "ingredient_ids"]].copy()
pp_rec_fields["ingredient_ids"] = pp_rec_fields["ingredient_ids"].apply(lambda x: x[1:-1]).str.split(", ").apply(lambda x: [int(y) for y in x])

pp_rec_fields.head()

In [12]:
# ORGANIZE ALL RATINGS BY RECIPE

recipe_ratings = {}
item_rate = pp_user[["items", "ratings"]]
for i in item_rate.iterrows():
    item_list = i[1]["items"]
    ratings_list = i[1]["ratings"]
    for j in range(len(item_list)):
        if item_list[j] not in recipe_ratings:
            recipe_ratings[item_list[j]] = [ratings_list[j]]
        else:
            recipe_ratings[item_list[j]].append(ratings_list[j])

In [13]:
# CREATING ESSENTIAL FIELDS WITH ALL RECIPES

recipe_stats = data[["id","minutes","n_steps", "n_ingredients"]]
recipe_stats = recipe_stats.merge(pp_rec_fields, on="id", how="left")
recipe_stats["id"]             = recipe_stats["id"].astype(int)
recipe_stats["minutes"]        = recipe_stats["minutes"].astype(int)
recipe_stats["n_steps"]        = recipe_stats["n_steps"].astype(int)
recipe_stats["n_ingredients"]  = recipe_stats["n_ingredients"].astype(int)
recipe_stats["ingredient_ids"] = recipe_stats["ingredient_ids"].apply(lambda x: x if isinstance(x, list) else [])
recipe_stats["ratings"]        = recipe_stats["id"].map(recipe_ratings).apply(lambda x: x if isinstance(x, list) else [])
recipe_stats.head()

,id,minutes,n_steps,n_ingredients,ingredient_ids,ratings
0,137739,55,11,7,"[7933, 4694, 4795, 3723, 840, 5006, 6270]","[5.0, 5.0]"
1,31490,30,9,6,"[5481, 6324, 2499, 4717, 6276, 1170]",[4.0]
2,112140,130,6,13,[],"[5.0, 5.0, 4.0]"
3,59389,45,11,11,"[1170, 4918, 6426, 5185, 7099, 5006, 6009, 627...","[4.0, 5.0]"
4,44061,190,5,8,[],"[5.0, 5.0]"

In [14]:
# BAYESIAN FOR ALL RATINGS

rating_len = recipe_stats["ratings"].apply(lambda x: len(x))
rating_tot = recipe_stats["ratings"].apply(lambda x: sum(x))
rating_avg = recipe_stats["ratings"].apply(lambda x: 0 if len(x) == 0 else sum(x) / len(x))
rating_tot_avg = rating_avg.mean()
rating_len_avg = rating_len.mean()
print(rating_tot_avg, rating_len_avg)

recipe_stats["bayesian"] = recipe_stats["ratings"].apply(lambda x: (sum(x) + rating_tot_avg * rating_len_avg) / (len(x) + rating_len_avg))
recipe_stats.head()

1.776444144205202 1.7134352456645527

,id,minutes,n_steps,n_ingredients,ingredient_ids,ratings,bayesian
0,137739,55,11,7,"[7933, 4694, 4795, 3723, 840, 5006, 6270]","[5.0, 5.0]",3.512603
1,31490,30,9,6,"[5481, 6324, 2499, 4717, 6276, 1170]",[4.0],2.595906
2,112140,130,6,13,[],"[5.0, 5.0, 4.0]",3.616009
3,59389,45,11,11,"[1170, 4918, 6426, 5185, 7099, 5006, 6009, 627...","[4.0, 5.0]",3.243310
4,44061,190,5,8,[],"[5.0, 5.0]",3.512603

In [50]:
bay = recipe_stats[["id", "bayesian"]]
bay = bay.sort_values(by="bayesian", ascending=False)
bay_dict = bay[:10000].set_index("id")["bayesian"].to_dict()

with open('data.pkl', 'wb') as file:
    pickle.dump(bay_dict, file)

bay_dict

{31024: 4.888896146637364,
 81311: 4.878092117385156,
 113588: 4.866958490703674,
 63482: 4.86130381277613,
 84680: 4.859613375767667,
 82100: 4.853156278730203,
 153429: 4.84738147736143,
 361: 4.839773917864575,
 96770: 4.836167564075291,
 6682: 4.834833042997736,
 45374: 4.831931041973422,
 75785: 4.8311594554894945,
 113937: 4.830752518582028,
 130399: 4.829480336367656,
 35495: 4.827028373915179,
 141365: 4.827028373915179,
 164559: 4.825835511766508,
 137287: 4.825835511766508,
 163792: 4.823864454441163,
 39272: 4.822316975351482,
 36523: 4.821363643682276,
 172390: 4.820767526620506,
 118206: 4.820164883038708,
 71071: 4.819641940890756,
 80022: 4.819641940890756,
 97466: 4.817661967704864,
 54631: 4.817539554201845,
 68338: 4.8173417321852545,
 170672: 4.8144468912153995,
 153976: 4.8141125664528115,
 53173: 4.811116399961962,
 121511: 4.810558966426646,
 153988: 4.810431859517403,
 32068: 4.810200918906,
 16834: 4.809378228873309,
 170446: 4.808758347367712,
 75591: 4.8084350000633345,
 32792: 4.806827355041383,
 65619: 4.806505798885444,
 31341: 4.806505798885444,
 132445: 4.8034424894623875,
 101783: 4.802017531954078,
 101669: 4.800697597727398,
 72311: 4.800512624461808,
 129659: 4.800512624461808,
 86420: 4.800208522415273,
 95918: 4.800157544521568,
 90536: 4.7977287266353255,
 107671: 4.7956688493889255,
 147342: 4.795078990311167,
 90165: 4.793236842476724,
 13467: 4.793236842476724,
 66421: 4.792493760899646,
 11954: 4.790650084713871,
 94021: 4.7894094317005775,
 33305: 4.7894094317005775,
 284: 4.7893410654019775,
 79691: 4.7885624398995486,
 125928: 4.787605841954524,
 28627: 4.7870135862439565,
 116421: 4.785195787069391,
 37450: 4.78477990424665,
 82121: 4.781396257595735,
 147654: 4.781316057007796,
 19549: 4.780998805924824,
 81214: 4.780457757046487,
 112180: 4.776844033695597,
 120053: 4.776844033695597,
 75141: 4.7765039880218145,
 85162: 4.7765039880218145,
 126298: 4.7765039880218145,
 34759: 4.7765039880218145,
 9513: 4.7765039880218145,
 135071: 4.775218416088214,
 85206: 4.774513194992692,
 40743: 4.773529120137682,
 136244: 4.773529120137682,
 96260: 4.773529120137682,
 141807: 4.772811780830992,
 139267: 4.772811780830992,
 176870: 4.772811780830992,
 145380: 4.772811780830992,
 111034: 4.772811780830992,
 106121: 4.772811780830992,
 90215: 4.772775120362758,
 60561: 4.7716957578870955,
 147374: 4.771116674127076,
 106910: 4.770022494941609,
 74368: 4.770022494941609,
 106142: 4.769797343753876,
 82291: 4.7686206696159195,
 147645: 4.768020458679655,
 51508: 4.76736345769744,
 8523: 4.767079119390895,
 97344: 4.767079119390895,
 114569: 4.767079119390895,
 5299: 4.766848756509238,
 89177: 4.76466462834432,
 82934: 4.76461401620329,
 30989: 4.76461401620329,
 176271: 4.764180069228924,
 150412: 4.7637719872404425,
 18209: 4.762770757522534,
 55066: 4.761700581474594,
 32722: 4.7613403986186995,
 106697: 4.7613403986186995,
 31607: 4.7613403986186995,
 71589: 4.760198175736337,
 13779: 4.75958237319161,
 19086: 4.759264991173832,
 107224: 4.75726942415134,
 155665: 4.757178886773743,
 69194: 4.756824357040337,
 115298: 4.756824357040337,
 108964: 4.756824357040337,
 12584: 4.756824357040337,
 134849: 4.756824357040337,
 38291: 4.756824357040337,
 86415: 4.756824357040337,
 66337: 4.756824357040337,
 145518: 4.755802495646985,
 130105: 4.755802495646985,
 116491: 4.755802495646985,
 48614: 4.755046800870341,
 151526: 4.754465262243048,
 36484: 4.754003896599342,
 162789: 4.754003896599342,
 47092: 4.753628942295029,
 34331: 4.753318201517696,
 70529: 4.753318201517696,
 151474: 4.753318201517696,
 101791: 4.7530564798258705,
 138873: 4.752833026130291,
 127634: 4.751969226616081,
 100654: 4.749381996712785,
 76669: 4.749219515839979,
 10184: 4.748354015700734,
 149777: 4.748089140132811,
 67440: 4.747921936783781,
 119805: 4.747921936783781,
 74633: 4.747400448510489,
 121777: 4.7471822685057505,
 11283: 4.7468029476401625,
 129693: 4.7468029476401625,
 44857: 4.7468029476401625,
 172003: 4.746305611935417,
 129817: 4.746305611935417,
 61307: 4.746305611935417,
 57868: 4.745927500670105,
 112286: 4.745725675567877,
 164861: 4.7456250401101325,
 103904: 4.7456250401101325,
 66852: 4.7456250401101325,
 23221: 4.7456250401101325,
 154851: 4.7456250401101325,
 20006: 4.7456250401101325,
 9054: 4.7456250401101325,
 100477: 4.7456250401101325,
 64685: 4.7456250401101325,
 10550: 4.7456250401101325,
 49085: 4.7456250401101325,
 75439: 4.7456250401101325,
 48398: 4.744317643090445,
 132128: 4.743916866316127,
 89274: 4.743455266069016,
 65482: 4.742892474110936,
 106555: 4.742284300985251,
 136789: 4.741439914879184,
 77073: 4.741213037617832,
 15929: 4.740685002657184,
 70951: 4.740603020230536,
 124818: 4.740603020230536,
 92002: 4.739454014667666,
 31881: 4.739454014667666,
 52535: 4.739454014667666,
 100396: 4.739454014667666,
 40335: 4.739454014667666,
 8252: 4.739320432214465,
 167268: 4.738690181284094,
 112: 4.737984878670234,
 104640: 4.737984878670234,
 157740: 4.737506848532923,
 145411: 4.736388729118926,
 27752: 4.736040167834152,
 172969: 4.736040167834152,
 166804: 4.736040167834152,
 39661: 4.736040167834152,
 91520: 4.735909831359152,
 154054: 4.735626118213846,
 135391: 4.735492982708416,
 115844: 4.735017780391184,
 147615: 4.734564891399192,
 67666: 4.73455597963321,
 165343: 4.734458411093462,
 152279: 4.73334436542373,
 7524: 4.73334436542373,
 24167: 4.73334436542373,
 130233: 4.73334436542373,
 112454: 4.73334436542373,
 88105: 4.73334436542373,
 166876: 4.73334436542373,
 94750: 4.73334436542373,
 135848: 4.7333397318354224,
 48733: 4.7333397318354224,
 68395: 4.7333397318354224,
 28206: 4.7333397318354224,
 46722: 4.7333397318354224,
 141554: 4.733336810742316,
 165946: 4.731238380400548,
 74804: 4.731238380400548,
 33065: 4.730426019984848,
 84490: 4.730217104912984,
 89598: 4.730217104912984,
 176345: 4.729614124412953,
 11102: 4.728881130875456,
 81857: 4.728530434679183,
 81837: 4.728530434679183,
 58932: 4.728530434679183,
 151465: 4.728530434679183,
 86018: 4.728530434679183,
 82078: 4.728530434679183,
 30473: 4.728530434679183,
 175469: 4.728173070849721,
 37088: 4.728173070849721,
 84796: 4.728173070849721,
 130387: 4.727973853489304,
 12178: 4.727846824136555,
 9771: 4.727758764409944,
 113698: 4.72630856462093,
 19946: 4.72565797212834,
 141087: 4.72565797212834,
 113961: 4.72555814438814,
 177733: 4.724908932337005,
 11636: 4.724908932337005,
 120221: 4.724908932337005,
 128192: 4.724908932337005,
 39650: 4.724908932337005,
 163824: 4.724908932337005,
 156061: 4.724908932337005,
 54041: 4.724908932337005,
 54293: 4.724035215187011,
 150946: 4.723749574883434,
 38973: 4.723289170155608,
 55636: 4.722487759786158,
 89741: 4.722487759786158,
 174552: 4.72172951325043,
 87426: 4.721371440277591,
 129439: 4.7209653761016925,
 156352: 4.720722780873796,
 173270: 4.719975176106524,
 28794: 4.719919658355898,
 172947: 4.719817771440831,
 55887: 4.719817771440831,
 38696: 4.719817771440831,
 151975: 4.719817771440831,
 106798: 4.719817771440831,
 164107: 4.719817771440831,
 82746: 4.719817771440831,
 14520: 4.719817771440831,
 95004: 4.719817771440831,
 17129: 4.719817771440831,
 58884: 4.719817771440831,
 97415: 4.71925418026174,
 95811: 4.718368148817245,
 169597: 4.718368148817245,
 67005: 4.718368148817245,
 64851: 4.718368148817245,
 135287: 4.718368148817245,
 43154: 4.717520503315904,
 52859: 4.717520503315904,
 53194: 4.717260319950063,
 89665: 4.716964334987815,
 14230: 4.716964334987815,
 152500: 4.716964334987815,
 141290: 4.716571356682687,
 61366: 4.715898907839311,
 13367: 4.715270742437544,
 168258: 4.714005701607046,
 91200: 4.7137633916455055,
 20706: 4.713619198752094,
 96642: 4.713619198752094,
 57659: 4.713148138233838,
 36846: 4.713148138233838,
 113704: 4.713148138233838,
 127847: 4.713148138233838,
 84482: 4.713148138233838,
 41971: 4.713148138233838,
 173887: 4.712797551355323,
 174138: 4.712797551355323,
 45708: 4.712797551355323,
 67259: 4.712797551355323,
 50409: 4.712797551355323,
 122927: 4.712797551355323,
 52425: 4.712797551355323,
 38432: 4.712772105892304,
 4152: 4.711376005182666,
 32114: 4.7109685057497686,
 79316: 4.710348323498659,
 98791: 4.70983738504603,
 165260: 4.70983738504603,
 47467: 4.70983738504603,
 146982: 4.709270828856342,
 74284: 4.7088855343937235,
 77723: 4.7088855343937235,
 34390: 4.7088855343937235,
 74332: 4.7088855343937235,
 44396: 4.708505845996959,
 62363: 4.707858566845796,
 73956: 4.707677497825968,
 66218: 4.707415436801442,
 37110: 4.707415436801442,
 35465: 4.707415436801442,
 60225: 4.707415436801442,
 87117: 4.707415436801442,
 87254: 4.707415436801442,
 36366: 4.707415436801442,
 108918: 4.707415436801442,
 127080: 4.707174749078173,
 54644: 4.706805267530939,
 110420: 4.706542520161583,
 173688: 4.706464668047474,
 140898: 4.706366999564918,
 100979: 4.705514274542297,
 177328: 4.704845521563616,
 74890: 4.704845521563616,
 37610: 4.704845521563616,
 158289: 4.704845521563616,
 68254: 4.704845521563616,
 120429: 4.704845521563616,
 47091: 4.704845521563616,
 102773: 4.704845521563616,
 25774: 4.703157976509477,
 6549: 4.703157976509477,
 141777: 4.703157976509477,
 56419: 4.703157976509477,
 46468: 4.7023422451001,
 155937: 4.7023422451001,
 93227: 4.7023422451001,
 169138: 4.702224579536051,
 131506: 4.702190255669851,
 19316: 4.701862905700603,
 108243: 4.701861423928633,
 124501: 4.7007044824329265,
 150197: 4.699848920320985,
 41295: 4.699819705537961,
 4683: 4.699776483381603,
 16284: 4.699706003278561,
 96114: 4.699706003278561,
 100365: 4.699706003278561,
 176544: 4.69957060474852,
 158237: 4.69957060474852,
 83754: 4.69957060474852,
 79621: 4.69957060474852,
 76063: 4.69957060474852,
 129471: 4.69957060474852,
 112654: 4.69957060474852,
 105696: 4.69957060474852,
 13906: 4.699046984812601,
 15862: 4.69800188663905,
 94216: 4.696908683701714,
 30339: 4.696908683701714,
 93194: 4.696850682013632,
 50115: 4.696850682013632,
 79985: 4.696850682013632,
 119044: 4.696749968213068,
 67898: 4.695930067031139,
 107051: 4.69557634764649,
 162691: 4.69557634764649,
 10183: 4.69557634764649,
 47329: 4.69557634764649,
 172115: 4.69557634764649,
 72606: 4.69557634764649,
 7004: 4.695110418718493,
 83438: 4.694905186228778,
 62794: 4.694689274066402,
 87159: 4.694449626648321,
 102888: 4.6944470957753675,
 75061: 4.6944470957753675,
 141217: 4.693094149326314,
 140963: 4.692446853155076,
 42155: 4.692446853155076,
 158076: 4.692446853155076,
 15792: 4.692446853155076,
 97918: 4.692379492316666,
 84679: 4.692365501130135,
 42988: 4.692356073425891,
 134105: 4.69234928957051,
 48236: 4.691707376889408,
 156978: 4.691567783142167,
 38413: 4.691019347641673,
 53408: 4.690636205009113,
 92216: 4.690636205009113,
 149629: 4.690557797110007,
 93365: 4.689928718701974,
 112978: 4.689687152301692,
 84437: 4.688806985821267,
 132217: 4.688689446795424,
 28774: 4.68844766915394,
 149428: 4.6884437580661205,
 124517: 4.688182775216398,
 112191: 4.688182775216398,
 139353: 4.688182775216398,
 8744: 4.688182775216398,
 54796: 4.688182775216398,
 17782: 4.688182775216398,
 37714: 4.688182775216398,
 70646: 4.688182775216398,
 19257: 4.688182775216398,
 59072: 4.688182775216398,
 81601: 4.688182775216398,
 68985: 4.688182775216398,
 58353: 4.688182775216398,
 173147: 4.688182775216398,
 100032: 4.688182775216398,
 147694: 4.6878587381260575,
 150763: 4.687743280202288,
 135400: 4.685473456403843,
 33876: 4.685066521206204,
 37858: 4.685066521206204,
 156589: 4.685066521206204,
 177509: 4.685066521206204,
 36981: 4.685066521206204,
 166709: 4.685066521206204,
 94636: 4.685066521206204,
 124076: 4.685066521206204,
 76230: 4.685066521206204,
 28710: 4.685066521206204,
 20324: 4.685066521206204,
 123238: 4.685066521206204,
 92313: 4.685066521206204,
 80109: 4.685066521206204,
 63642: 4.685066521206204,
 160494: 4.685066521206204,
 13572: 4.685066521206204,
 90030: 4.684656989700876,
 46132: 4.684656989700876,
 36359: 4.684438679847764,
 66593: 4.684287712026387,
 131089: 4.683644993315151,
 100001: 4.683393430148894,
 46833: 4.683393430148894,
 97269: 4.682738745283114,
 4294: 4.682738745283114,
 16960: 4.682738745283114,
 38535: 4.682738745283114,
 103303: 4.6822957158734955,
 46172: 4.6822957158734955,
 175886: 4.682061509052898,
 106926: 4.682061509052898,
 168561: 4.682013590025504,
 46522: 4.681333206303312,
 122488: 4.680933801987505,
 169085: 4.680933801987505,
 160180: 4.680933801987505,
 108605: 4.680933801987505,
 35635: 4.680933801987505,
 39913: 4.6797248401419695,
 15491: 4.6794933288275145,
 132583: 4.6794933288275145,
 114131: 4.6794933288275145,
 73724: 4.679334389378085,
 44040: 4.678891014683963,
 25058: 4.6783170541197805,
 53353: 4.6783170541197805,
 134237: 4.6783170541197805,
 24040: 4.677880275320993,
 145727: 4.677338398268868,
 120742: 4.677338398268868,
 163739: 4.677338398268868,
 168476: 4.677152492907235,
 68273: 4.676918978865637,
 72387: 4.675803391879773,
 35402: 4.675721715978586,
 167228: 4.675410119034318,
 133911: 4.675190373097192,
 91675: 4.675190373097192,
 29338: 4.67510048270536,
 3459: 4.6746826051984005,
 67106: 4.673762176268523,
 68663: 4.6736224999241065,
 89007: 4.6736224999241065,
 5289: 4.6736224999241065,
 139149: 4.673386841416854,
 64659: 4.673049220173534,
 63064: 4.672213241280084,
 92748: 4.671913138246869,
 15822: 4.6717678133919,
 48069: 4.6715708919699175,
 106520: 4.671388609108768,
 74986: 4.670527581795249,
 91233: 4.670413705537331,
 118365: 4.669526094516092,
 30601: 4.669526094516092,
 146032: 4.669526094516092,
 52093: 4.669526094516092,
 34731: 4.669526094516092,
 137093: 4.669526094516092,
 168361: 4.669526094516092,
 144103: 4.669526094516092,
 143838: 4.669526094516092,
 138927: 4.669526094516092,
 484: 4.669526094516092,
 172114: 4.669526094516092,
 13071: 4.669526094516092,
 21450: 4.669526094516092,
 95779: 4.669526094516092,
 121865: 4.669526094516092,
 24547: 4.669526094516092,
 57697: 4.669526094516092,
 48540: 4.669526094516092,
 117464: 4.669526094516092,
 69469: 4.669526094516092,
 114436: 4.669526094516092,
 19349: 4.669526094516092,
 3102: 4.669526094516092,
 12072: 4.669526094516092,
 134304: 4.669526094516092,
 177500: 4.669526094516092,
 150292: 4.669212358006318,
 164675: 4.669090945418972,
 69592: 4.669090945418972,
 157585: 4.669090945418972,
 13160: 4.669090945418972,
 118613: 4.669090945418972,
 158071: 4.669090945418972,
 30313: 4.669090945418972,
 130475: 4.669090945418972,
 112508: 4.669090945418972,
 50741: 4.669090945418972,
 34744: 4.669090945418972,
 8479: 4.669090945418972,
 17987: 4.669090945418972,
 158546: 4.669090945418972,
 34417: 4.669090945418972,
 98055: 4.669090945418972,
 123686: 4.669090945418972,
 119408: 4.669090945418972,
 65677: 4.669090945418972,
 56555: 4.669090945418972,
 95895: 4.669090945418972,
 46796: 4.668770745670311,
 80011: 4.668770745670311,
 94045: 4.668770745670311,
 107507: 4.668770745670311,
 151057: 4.668770745670311,
 4932: 4.668770745670311,
 89683: 4.668770745670311,
 84855: 4.668770745670311,
 11478: 4.668770745670311,
 9863: 4.668770745670311,
 67020: 4.668770745670311,
 90196: 4.668770745670311,
 10316: 4.668770745670311,
 152904: 4.668770745670311,
 103500: 4.668770745670311,
 144115: 4.668770745670311,
 38308: 4.668770745670311,
 102500: 4.668770745670311,
 104723: 4.668770745670311,
 99184: 4.668525261667468,
 124192: 4.668525261667468,
 6893: 4.668525261667468,
 99914: 4.668525261667468,
 93179: 4.668525261667468,
 159761: 4.668525261667468,
 54578: 4.668525261667468,
 73694: 4.668525261667468,
 176248: 4.66833107434872,
 60058: 4.66833107434872,
 48415: 4.66833107434872,
 157324: 4.66833107434872,
 102112: 4.66833107434872,
 106807: 4.66833107434872,
 129723: 4.668173626156574,
 48842: 4.668043391898923,
 154545: 4.668043391898923,
 154562: 4.667933877194949,
 139718: 4.667933877194949,
 26923: 4.667840501837112,
 32438: 4.6677599429542065,
 103100: 4.6677599429542065,
 120746: 4.6677599429542065,
 37265: 4.6676279935587806,
 92217: 4.667480634747414,
 21075: 4.667441066309317,
 161396: 4.667441066309317,
 14451: 4.667314999796736,
 77442: 4.667314999796736,
 36503: 4.667224232257919,
 84120: 4.667205377202096,
 17320: 4.667059317339163,
 29638: 4.664413216031549,
 91587: 4.662739710524825,
 66643: 4.661145036363519,
 148228: 4.661145036363519,
 161086: 4.660921089960714,
 7612: 4.66080498867799,
 37609: 4.66080498867799,
 158151: 4.6604203089034,
 128087: 4.6604203089034,
 4489: 4.659981592766849,
 30066: 4.659981592766849,
 166212: 4.659529643404788,
 136641: 4.65888906510959,
 112635: 4.65888906510959,
 74052: 4.658835168909679,
 17321: 4.658218613107447,
 146204: 4.658196972936211,
 127437: 4.658196972936211,
 138627: 4.658036822030921,
 72975: 4.657660046603893,
 113774: 4.65736967761779,
 112656: 4.65736967761779,
 139238: 4.656921751492975,
 115443: 4.656798353727957,
 30713: 4.656756031976454,
 146821: 4.656363271630969,
 34200: 4.656363271630969,
 56364: 4.656363271630969,
 22426: 4.656363271630969,
 118199: 4.656363271630969,
 46516: 4.656363271630969,
 164568: 4.656363271630969,
 108728: 4.655754335192036,
 34884: 4.655557449831874,
 115658: 4.655144860220381,
 58497: 4.6551125274588285,
 101812: 4.6551125274588285,
 72580: 4.6551125274588285,
 18609: 4.6551125274588285,
 102971: 4.6551125274588285,
 45237: 4.654463277141431,
 114044: 4.653748951807421,
 109481: 4.653695984482933,
 101084: 4.653516169386909,
 150299: 4.653516169386909,
 3225: 4.653516169386909,
 121648: 4.653516169386909,
 133588: 4.653516169386909,
 34602: 4.65269371457107,
 13425: 4.652604329785597,
 21122: 4.651830300377942,
 126870: 4.651830300377942,
 145152: 4.651830300377942,
 127024: 4.6514079785966365,
 16342: 4.6514079785966365,
 90910: 4.6514079785966365,
 72945: 4.6514079785966365,
 34014: 4.6514079785966365,
 15873: 4.6514079785966365,
 13462: 4.6514079785966365,
 170173: 4.6514079785966365,
 63216: 4.6514079785966365,
 41109: 4.6514079785966365,
 27606: 4.6514079785966365,
 22663: 4.6514079785966365,
 126578: 4.6514079785966365,
 82177: 4.6514079785966365,
 157603: 4.6514079785966365,
 52199: 4.6514079785966365,
 66671: 4.6514079785966365,
 103777: 4.6514079785966365,
 98766: 4.6514079785966365,
 88035: 4.6514079785966365,
 92059: 4.6514079785966365,
 63146: 4.6514079785966365,
 147814: 4.6514079785966365,
 52633: 4.6514079785966365,
 66682: 4.6514079785966365,
 106975: 4.651107839953469,
 15173: 4.651008106650577,
 56077: 4.6507284786900716,
 110716: 4.650680593600858,
 49228: 4.650448757872626,
 41169: 4.650448757872626,
 150138: 4.6498481063392685,
 17877: 4.649575472530094,
 83992: 4.649337731485591,
 98923: 4.649337731485591,
 117827: 4.649205596432605,
 82451: 4.648602787252218,
 141873: 4.648494798665295,
 36434: 4.648494798665295,
 111201: 4.648494798665295,
 85545: 4.648494798665295,
 169319: 4.648494798665295,
 138801: 4.648494798665295,
 81679: 4.648494798665295,
 130727: 4.648494798665295,
 36625: 4.648494798665295,
 29772: 4.648494798665295,
 141784: 4.648494798665295,
 50313: 4.648494798665295,
 138541: 4.648494798665295,
 157891: 4.648494798665295,
 151217: 4.648494798665295,
 62575: 4.648494798665295,
 5343: 4.648494798665295,
 127419: 4.648494798665295,
 140335: 4.648494798665295,
 34965: 4.648494798665295,
 29044: 4.648494798665295,
 68351: 4.648494798665295,
 141244: 4.648494798665295,
 110190: 4.648494798665295,
 4446: 4.648494798665295,
 111828: 4.648494798665295,
 73780: 4.648494798665295,
 32987: 4.648494798665295,
 119743: 4.648494798665295,
 153339: 4.648494798665295,
 43722: 4.648494798665295,
 143647: 4.648494798665295,
 128433: 4.648494798665295,
 77430: 4.648226283308678,
 59871: 4.6477485738458375,
 174602: 4.6477485738458375,
 53667: 4.6477485738458375,
 100387: 4.647512706915273,
 32845: 4.647397047790072,
 164037: 4.64583851942119,
 33965: 4.64583851942119,
 42579: 4.64583851942119,
 140455: 4.64583851942119,
 138444: 4.64583851942119,
 160396: 4.645835316214224,
 171328: 4.645516910093428,
 84216: 4.644883680899301,
 29681: 4.644883680899301,

In [15]:
# BEGIN TRAINING DATA

train = pd.read_csv("interactions_train.csv")
train = train[["recipe_id", "rating"]]
train["recipe_id"] = train["recipe_id"].astype(int)
train["rating"] = train["rating"].astype(int)

train.head()

   recipe_id  rating
0       4684       5
1        517       5
2       7435       5
3        278       4
4       3431       5

In [16]:
# ORGANIZE ALL TRAINING RATINGS BY RECIPE
train_ratings = {}
for i in train.iterrows():
    id = i[1]["recipe_id"]
    rating = i[1]["rating"]
    if id in train_ratings:
        train_ratings[id].append(rating)
    else:
        train_ratings[id] = [rating]

In [28]:
# EXTRACTING ESSENTIAL FIELDS
train_features = data[["id","minutes","n_steps", "n_ingredients"]].copy()
train_features["id"] = train_features["id"].astype(int)
train_features["minutes"] = train_features["minutes"].astype(int)
train_features["n_steps"] = train_features["n_steps"].astype(int)
train_features["n_ingredients"] = train_features["n_ingredients"].astype(int)
train_features["ratings"] = train_features["id"].map(train_ratings)
train_features = train_features.dropna()
train_features.head()

       id  minutes  n_steps  n_ingredients    ratings
0  137739       55       11              7  [5, 5, 5]
1   31490       30        9              6  [0, 4, 5]
3   59389       45       11             11        [4]
5    5289        0        4              4     [5, 5]
8   70971      180        8              6     [5, 5]

In [37]:
train_avg_len = train_features["ratings"].apply(lambda x: len(x)).mean()
train_avg_rating = train_features["ratings"].apply(lambda x: sum(x) / len(x)).mean()

train_features["bayesian"] = train_features["ratings"].apply(lambda x: (train_avg_len * train_avg_rating + sum(x)) / (train_avg_len + len(x)))
train_features.head()

       id  minutes  n_steps  n_ingredients    ratings  bayesian
0  137739       55       11              7  [5, 5, 5]  4.706211
1   31490       30        9              6  [0, 4, 5]  3.889181
3   59389       45       11             11        [4]  4.409115
5    5289        0        4              4     [5, 5]  4.659898
8   70971      180        8              6     [5, 5]  4.659898